---
- name: "SONARQUBE | Set up directories"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0750"
  with_items:
    - "{{ sonarqube_skeleton_paths }}"
  tags:
    - sonarqube_configure
  become: true

- name: "SONARQUBE | Write configuration files"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ sonarqube_config_path | expanduser | realpath  }}/{{ item  }}"
    mode: '0640'
  with_items:
    - "{{ sonarqube_configuration_files }}"
  tags:
    - sonarqube_configure
