---
- name: "SONARQUBE | Ensure sonarqube is running"
  community.docker.docker_compose:
    project_src: "{{ sonarqube_config_path | expanduser | realpath }}"
    build: false
  tags:
    - sonarqube_install
